// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksqqrrabctuptasdlzka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzcXFycmFiY3R1cHRhc2RsemthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjM3MTMsImV4cCI6MjA2NjI5OTcxM30.Z3IOEsHSXW4LcuYdS5NyGebDdmN-_gnCxL5nwEQ--Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);